# SPDX-License-Identifier: MIT
# Copyright (c) 2026 WaveCord contributors
"""Type stubs for the compiled Rust extension."""

from typing import Any

__version__: str

class WaveCordError(Exception):
    """Base error for all WaveCord failures (connection, REST, protocol)."""

async def ping() -> str: ...
def decode_message(text: str, version: str = ...) -> dict[str, Any] | None: ...

class Node:
    def __init__(
        self,
        host: str,
        port: int,
        password: str,
        user_id: str,
        *,
        secure: bool = ...,
        client_name: str | None = ...,
        session_id: str | None = ...,
        version: str | None = ...,
        reconnect: bool = ...,
        resume: bool = ...,
        resume_timeout: int = ...,
    ) -> None: ...
    async def connect(self) -> None: ...
    def is_connected(self) -> bool: ...
    async def version(self) -> str | None: ...
    async def session_id(self) -> str | None: ...
    async def next_event(self) -> str | None: ...
    async def next_events(self, max_n: int = ...) -> list[str] | None: ...
    async def play(
        self,
        guild_id: str,
        encoded: str,
        *,
        no_replace: bool = ...,
        start_ms: int | None = ...,
        end_ms: int | None = ...,
        volume: int | None = ...,
        paused: bool | None = ...,
    ) -> dict[str, Any] | None: ...
    async def stop(self, guild_id: str) -> dict[str, Any] | None: ...
    async def set_pause(self, guild_id: str, paused: bool) -> dict[str, Any] | None: ...
    async def set_volume(self, guild_id: str, volume: int) -> dict[str, Any] | None: ...
    async def seek(self, guild_id: str, position_ms: int) -> dict[str, Any] | None: ...
    async def update_voice(
        self,
        guild_id: str,
        token: str,
        endpoint: str,
        session_id: str,
        channel_id: str | None = ...,
    ) -> dict[str, Any] | None: ...
    async def set_filters(
        self, guild_id: str, filters: dict[str, Any]
    ) -> dict[str, Any] | None: ...
    async def destroy(self, guild_id: str) -> None: ...
    async def load_tracks(self, identifier: str) -> dict[str, Any]: ...
    async def info(self) -> dict[str, Any]: ...
    async def decode_track(self, encoded: str) -> dict[str, Any]: ...
    async def load_search(self, query: str, types: str = ...) -> dict[str, Any]: ...
    async def lyrics(
        self, encoded: str, skip_track_source: bool = ...
    ) -> dict[str, Any] | None: ...
    async def current_lyrics(
        self, guild_id: str, skip_track_source: bool = ...
    ) -> dict[str, Any] | None: ...
    async def set_sponsorblock_categories(self, guild_id: str, categories: list[str]) -> None: ...
    async def routeplanner_status(self) -> dict[str, Any] | None: ...
    async def routeplanner_free(self, address: str) -> None: ...
    async def routeplanner_free_all(self) -> None: ...
